configfile: "config/config.yaml"
include: "rules/common.py"

include: "rules/DownloadBAM.smk"
include: "rules/GetGeneAnnotation.smk"
include: "rules/GetCountTables.smk"
include: "rules/RunSTM.smk"
#include: "rules/ExpressionAnalysis.smk"
include: "rules/RunTests.smk"
include: "rules/DifferentialSplicing.smk"
include: "rules/Develop.smk"

localrules:
    all,
    DownloadFromGTEx_Brain_Cortex,
    DownloadFromGTEx_Muscle_Skeletal,
    DownloadFromGTEx_Whole_Blood,
    DownloadFromGTEx_Liver,
    DownloadHg38Ref,


rule all:
    input:
        #expand("stm_models/{gene}/{gene}.sgom_K{knum}.rds", 
        #       gene=genes,
        #       knum=[3, 5, 10]
        #),
        expand("stm_models/{gene}/{gene}.sgom_K{knum}.rds", 
          gene=["CERCAM", "IDH3B", "GRHPR", "SNAP25", "FLNA", "RPN2", "NDRG4", "MORF4L2", "CMC1",
                "PKM", "NPM3", "FGF8", "CMC2", "APOE", "CKS2"], 
          knum=[3, 5, 10, 2]
        ),        
        #expand("stm_models/{gene}/{gene}.{mode}_{tissue}.sgom_K{knum}.rds",
        #        mode = ["no", "one_of", "minus_one_of"],
        #        gene = ["TPM3", "SRSF3"], 
        #        tissue = ["Muscle_Skeletal", "Whole_Blood", "Brain_Cortex"],
        #        knum=[3, 5, 10]
        #        )
        
rule DifferentialSplicing:
    input:
        "DifferentialSplicing/rMATS/Brain_Cortex_v_Muscle_Skeletal_female_test/output/summary.txt",
        "DifferentialSplicing/rMATS/Brain_Cortex_v_Muscle_Skeletal_train/output/summary.txt",
        "DifferentialSplicing/leafcutter/Brain_Cortex_v_Muscle_Skeletal_female_test/output/leafcutter_cluster_significance.txt",
        "DifferentialSplicing/leafcutter/Brain_Cortex_v_Muscle_Skeletal_train/output/leafcutter_cluster_significance.txt",
        "DifferentialSplicing/leafcutter/juncfiles/Brain_Cortex_v_Muscle_Skeletal/cluster_annotation.tab.gz"
        #"DifferentialSplicing/rMATS/Whole_Blood_v_Liver_female_test/output/summary.txt",
        #"DifferentialSplicing/rMATS/Whole_Blood_v_Liver_train/output/summary.txt",
        #"DifferentialSplicing/leafcutter/Whole_Blood_v_Liver_female_test/output/leafcutter_cluster_significance.txt",
        #"DifferentialSplicing/leafcutter/Whole_Blood_v_Liver_train/output/leafcutter_cluster_significance.txt"
        
        
rule tests:
    input:
        expand("Tests/PKM/stm_models/SubsetRegion.sgom_K{knum}.rds", knum=[2, 3, 5, 10]),
        expand("Tests/PKM/stm_models/SubsetRegion_train.sgom_K{knum}.rds", knum=[2, 3, 5, 10]),
        expand("Tests/PKM/stm_models/SubsetTissues.sgom_K{knum}.rds", knum=[2, 3, 5, 10]),
        expand("Tests/PKM/stm_models/SubsetTissues_train.sgom_K{knum}.rds", knum=[2, 3, 5, 10]),
        expand("Tests/PKM/stm_models/SubsetTissues_plus_one.sgom_K{knum}.rds", knum=[2, 3, 5, 10]),
        expand("Tests/PKM/stm_models/SubsetTissues_train_plus_one.sgom_K{knum}.rds", knum=[2, 3, 5, 10]),
        expand("Tests/{gene}/stm_models/Training.sgom_K{knum}.rds", gene = ["PKM", "TPM3", "SRSF3"], knum=[2, 3, 5, 10])
