# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

scratch: "/scratch/midway2/cnajar/"

samples: config/samples.tsv

rMATS: "/home/cnajar/rmats-turbo/rmats.py"
R: "/software/R-4.1.0-el8-x86_64/bin/R"
Rscript: "/software/R-4.1.0-el7-x86_64/bin/Rscript" #"/software/R-4.1.0-el8-x86_64/bin/Rscript"
python: "/project2/mstephens/cfbuenabadn/anaconda3/bin/python"
picard: "/software/picard-2.21.8-el7-x86_64/bin/picard.jar"
kallisto: '/project2/mstephens/cfbuenabadn/software/kallisto/bin/kallisto'
QTLtools: "scripts/QTLtools"

gwas_coloc_chunks: 10
